home/urls.py
from operator import index
from unicodedata import name
from django.urls import path
from . import views

app_name = 'home' 
urlpatterns = [
    path('cadastro/', views.cadastrar, name='cadastrar'),
    path('login/', views.entrar, name='entrar'),
    path('', views.plataforma, name="index"),
    path('conta/', views.conta, name="conta"),
    path('logout/', views.logout, name="logout")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
import email
import http
from http.client import HTTPResponse
from pickletools import read_uint1
from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.contrib import messages

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import  logout as logout_django
from django.contrib.auth.decorators import login_required

"""
OBS: em caso de conflito do import com o nome da def... podemos importar com outro nome usando "as"
ex: from django.contrib.auth import login as login_qualquercoisa
"""

def cadastrar(request):
    if request.method == "GET":
        return render(request, 'home/login.html', context={'atualCad':True})
    else:
        username = request.POST.get('username')
        email = request.POST.get('email')
        senha = request.POST.get('senha')

        user = User.objects.filter(username = username).first()

        if user:
            return HttpResponse('Já existe um usuário com esse nome!')
        else:
            user = User.objects.create_user(username = username,   email = email,   password = senha)
            user.save()
                
            return HttpResponse('Usuário cadastrado com sucesso!')


def entrar(request):
    if request.method == "GET":
        return render(request, 'home/login.html')
    else:
        userLog = request.POST.get('userLog')
        senhaLog = request.POST.get('senhaLog')

        print(userLog, senhaLog)
        user = authenticate(username = userLog,   password = senhaLog)

        if user:
            login(request, user)

            return render(request, 'home/index.html', context={'atualIndex':True})
        else:
            messages.error(request, 'Usuário ou senha inválidos.')
            return render(request, 'home/login.html', context={'atualCad':True})



def plataforma(request):
    return render(request, 'home/index.html', context={'atualIndex':True})


@login_required(login_url="conta/")
def conta(request):
    return render(request, 'home/conta.html', context={'atualConta':True})


def logout(request):
    logout_django(request)
    return redirect('home:cadastrar')

home/templates/home/conta.html
{% load static %}
<!doctype html>
<html lang="pt-br">
    <head>
        <title>{%block title%}Conta{%endblock%}</title>
        <meta charset="utf-8">
        <link rel="stylesheet"      type="text/css" href="{% static 'home/css/conta.css' %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'home/css/normalize.css' %}">
        <meta name="viewport"       content="width=device-width, initial-scale=1.0">
        <meta name="author"         content="autor do site">
        <meta name="keywords"       content="palavras-separadas,por,virgula">
        <meta name="description"    content="descrição do site">
        <link rel="icon" type="image/png" href="logo/icon.png"/>
    </head>
    <body>
        {%block content%}

            {% include 'partials/nav.html' %}
            
            <section >
                <div class="info">
                    <h2 id="userName">Bem-vindo(a) ao seu perfil <span class="username">{{user}}</span>!</h2>
                    <a href="{%url 'home:logout'%}" class="button-inter item9"><span></span><span></span><span></span><span></span>SAIR DA CONTA</a>
                </div>
            </section>
        {%endblock%}
    </body>
    <script src="script/script.js"></script>
</html>

home/templates/home/index.html
{% load static %}
<!doctype html>
<html lang="pt-br">
    <head>
        <title>{%block 'titulo'%}Hello, World!{%endblock%}</title>
        <meta charset="utf-8">
        <link rel="stylesheet"      type="text/css" href="{% static 'home/css/index.css' %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'home/css/normalize.css' %}">
        <meta name="viewport"       content="width=device-width, initial-scale=1.0">
        <meta name="author"         content="autor do site">
        <meta name="keywords"       content="palavras-separadas,por,virgula">
        <meta name="description"    content="descrição do site">
        <link rel="icon" type="/" href="{% static 'home/img/icon.png' %}"/>
        <!-- fontaawesome -->
        <script src="https://kit.fontawesome.com/944a9ba2fe.js" crossorigin="anonymous"></script>
    </head>
    <body>
        {%block 'conteudo'%}
            {% include 'partials/nav.html' %}
            
            <div class="wrap">
                <h2>Hello, World!</h2>
            </div><!--wrap-->
        {%endblock%}
    </body>
</html>

home/templates/home/login.html
{% load static %}
<!doctype html>
<html lang="pt-br">
    <head>
        <title>{%block 'titulo'%}Faça Log-in!{%endblock%}</title>
        <meta charset="utf-8">
        <link rel="stylesheet"      type="text/css" href="{% static 'home/css/login.css' %}">
        <link rel="stylesheet"      type="text/css" href="{% static 'home/css/normalize.css' %}">
        <meta name="viewport"       content="width=device-width, initial-scale=1.0">
        <meta name="author"         content="autor do site">
        <meta name="keywords"       content="palavras-separadas,por,virgula">
        <meta name="description"    content="descrição do site">
        <link rel="icon" type="/" href="{% static 'home/img/icon.png' %}"/>
        <!-- fontaawesome -->
        <script src="https://kit.fontawesome.com/944a9ba2fe.js" crossorigin="anonymous"></script>
    </head>
    <body>
        {%block 'conteudo'%}
            <main>

                {% include 'partials/nav.html' %}
                
                <section>
                    <div class="box log-left">
                        <form action="{% url 'home:cadastrar' %}" method="POST">{% csrf_token %}
                            <h2>Cadastre-se já!</h2>
                            <div class="alertBox alertBoxCad"></div>

                            <div class="cad-wrapper">
                                <div class="label-float">
                                    <input id="username" type="text" name="username" required>
                                    <label id="usernameLabel" for="username">Username:</label>
                                </div><!--label-float-->
                                <div class="label-float">
                                    <input id="email" type="text" name="email" required>
                                    <label id="emailLabel" for="email">E-mail:</label>
                                </div><!--label-float-->
                                <div class="label-float">
                                    <input id="senha" type="password" name="senha" required>
                                    <label id="senhaLabel" for="senha">password:</label>
                                    <i id="verSenha" class="fa-solid fa-eye-low-vision"></i>
                                </div><!--label-float-->
                                <div class="label-float">
                                    <input id="senhaNv" type="password" name="senhaNv" required>
                                    <label id="senhaNvLabel" for="senhaNv">password again:</label>
                                    <i id="verSenhaNv" class="fa-solid fa-eye-low-vision"></i>
                                </div><!--label-float-->
                            </div><!--cad-wrapper-->
                            <!--<button onclick="cadastrar()" class="btn btn-cadastro">Cadastrar</button>-->
                            <input type="submit" onclick="cadastrar()" class="btn btn-cadastro" value="Cadastrar">
                        </form>
                    </div><!--log-left-->
                    <div class="box log-right">
                        <form  action="{% url 'home:entrar' %}" method="POST">{% csrf_token %}                           
                            <h2>Faça Log-in</h2>
                            <div class="alertBox alertBoxLog"></div>
    
                            <div class="cad-wrapper">
                                <div class="label-float">
                                    <input id="userLog" type="text" name="userLog" required>
                                    <label id="userLogLabel" for="userLog">Username:</label>
                                </div><!--label-float-->
                                <div class="label-float">
                                    <input id="senhaLog" type="password" name="senhaLog" required>
                                    <label id="senhaLogLabel" for="senhaLog">password:</label>
                                    <i id="verSenhaLog" class="fa-solid fa-eye-low-vision"></i>
                                </div><!--label-float-->
                            </div><!--cad-wrapper-->
                            <!--<button onclick="entrar()" class="btn btn-login">Entrar</button>-->
                            <input type="submit" onclick="entrar()" class="btn btn-login" value="Entrar">
                        </form>
                    </div><!--log-right-->
                </section>
            </main>
        {%endblock%}
    </body>
    <!-- JavaScript -->
    <script src="{% static 'home/script/script.js' %}"></script>
</html>

home/templates/partials/nav.html
<header>
    <div class="container">
        <nav class="navbar">
            <ul>

                <a href="{% url 'home:index' %}"><li {%if atualIndex%}class="atualPage"{%endif%}>Home</li></a>

                {% if user.is_authenticated %}
                    <a href="{% url 'home:conta' %}"><li {%if atualConta%}class="atualPage"{%endif%}>Conta</li></a>
                {% else %}
                    <a href="{% url 'home:cadastrar' %}"><li {%if atualCad%}class="atualPage"{%endif%}>Login</li></a>
                {% endif %}

            </ul>
        </nav><!--navbar-->
    </div><!-- container-->
</header>